name: slw
favicon: null
layout_spectrum: 0.6452557444572449
typography_spectrum: 0.8993626346345991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.057782272109761834
  lightness: 0.8778749250341207
  saturation: 0.3099966221489012
  rhythmicContrast: 0.5513368675019592
purpose: []
