name: slw
favicon: null
layout_spectrum: 0.00482
typography_spectrum: 1
title: Confessions of an Idea Junkie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00020e'
    - '#8dbde3'
    - '#538eb7'
    - '#315d7a'
    - '#eff6fc'
  brandStrength: 0.0625
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0
purpose: []
